# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1671c9aeacd9a6408d269bc7b3c51889aa9c982ae83ebffc6aa063c4de8a95198eab0ff9cd39ed8217bacc418ec6e8d836323ce1243a1e743b1d83a906821b9b

test:
  secret_key_base: 678bbe3de142159cb8d95b2affd9dd0ffb098b167e55c2de0fb6a8aa7c7867e37a45a7e9b873ed671ed12ecfe00c4a8e08e99c6ec4c7246845ff4476398e9626

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
